<link rel="stylesheet" href="./css/modules/parse/users.css">
<script>require(['./js/modules/parse/users.js']);</script>

<div class="row">
    <div class="col-md-5">
        <button class="create-user-button btn btn-info"
            type="button"
            data-toggle="collapse"
            data-target=".create-user-form"
            aria-expanded="false"
            aria-controls="collapseCreateUserForm">Create User</button>
        <div class="create-user-form collapse">
            <ul class="list-group">
                <li class="list-group-item">
                    <h6>Necessary fields</h6>
                    <div class="form-group">
                        <input type="text" class="username form-control" placeholder="username"/>
                    </div>
                    <div class="form-group">
                        <input type="password" class="password form-control" placeholder="password"/>
                    </div>
                    <div class="form-group">
                        <input type="email" class="email form-control" placeholder="email"/>
                    </div>
                </li>
                <li class="list-group-item custom-fields">
                    <h6>Custom fields</h6>

                    <button class="btn btn-warning"
                            type="button"
                            data-toggle="collapse"
                            data-target=".add-fields-form"
                            aria-expanded="false"
                            aria-controls="collapseAddFieldsForm">Add</button>
                    <div class="add-fields-form collapse">
                        <ul class="list-group">
                            <li class="list-group-item">
                                <div class="form-group">
                                    <input type="text" class="key form-control" placeholder="Key"/>
                                    <input type="text" class="value form-control" placeholder="Value"/>
                                </div>
                            </li>
                            <div class="row">
                                <div class="col-sm-1">
                                    <button class="more-fields-button btn btn-xs btn-warning" type="button">More fields</button>
                                </div>
                            </div>
                        </ul>
                    </div>
                </li>
                <li class="list-group-item">
                    <button type="button" class="btn btn-info create-user-button-submit">Submit</button>
                </li>
            </ul>

        </div>
    </div>
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>Current user</dt>
            <dd class="current-user">You are not logged in</dd>
        </dl>
    </div>
</div>
<div class="grid">
    <table class="table table-responsive">
        <thead><tr></tr></thead>
        <tbody></tbody>
    </table>
</div>