<link rel="stylesheet" href="./css/modules/parse/users.css">
<script>require(['./js/modules/parse/users.js']);</script>

<div class="row">
    <div class="col-md-5">
        <button class="create-user-button btn btn-info"
            type="button"
            data-toggle="collapse"
            data-target=".create-user-form"
            aria-expanded="false"
            aria-controls="collapseCreateUserForm">Create User</button>
        <div class="create-user-form collapse">
            <ul class="list-group">
                <li class="list-group-item">
                    <h6>Necessary fields</h6>
                    <div class="form-group">
                        <input type="text" class="username form-control" placeholder="username"/>
                    </div>
                    <div class="form-group">
                        <input type="password" class="password form-control" placeholder="password"/>
                    </div>
                    <div class="form-group">
                        <input type="email" class="email form-control" placeholder="email"/>
                    </div>
                </li>
                <li class="list-group-item custom-fields">
                    <h6>Custom fields</h6>

                    <button class="btn btn-warning"
                            type="button"
                            data-toggle="collapse"
                            data-target=".add-fields-form"
                            aria-expanded="false"
                            aria-controls="collapseAddFieldsForm">Add</button>
                    <div class="add-fields-form collapse">
                        <ul class="list-group">
                            <li class="list-group-item">
                                <div class="form-group">
                                    <input type="text" class="key form-control" placeholder="Key"/>
                                    <input type="text" class="value form-control" placeholder="Value"/>
                                </div>
                            </li>
                            <div class="row">
                                <div class="col-sm-1">
                                    <button class="more-fields-button btn btn-xs btn-warning" type="button">More fields</button>
                                </div>
                            </div>
                        </ul>
                    </div>
                </li>
                <li class="list-group-item">
                    <button type="button" class="btn btn-info create-user-button-submit">Submit</button>
                </li>
            </ul>

        </div>
    </div>
    <div class="col-md-2">
        <div class="row">
            <button type="button" class="col-xs-4 login-user-facebook btn btn-primary btn-xs"><i class="fa fa-sign-in"></i></button>
            <button type="button"
                    class="col-xs-4 login-user btn btn-success btn-xs"
                    data-toggle="collapse"
                    data-target=".login-user-form"
                    aria-expanded="false"
                    aria-controls="collapseLoginUserForm"><i class="fa fa-sign-in"></i></button>
            <button type="button" class="col-xs-4 logout-user btn btn-warning btn-xs"><i class="fa fa-sign-out"></i><button>
        </div>
        <div class="login-user-form collapse form-group">
            <input type="text" class="form-control log-in-username" placeholder="username"/>
            <input type="password" class="form-control log-in-password" placeholder="password"/>
            <button type="button" class="login-user-submit btn btn-info btn-xs form-control">Log in</button>
        </div>
    </div>
    <div class="col-md-4">
        <dl class="dl-horizontal">
            <dt>Current user</dt>
            <dd class="current-user">You are not logged in</dd>
        </dl>
    </div>
</div>
<div class="grid">
    <table class="table table-responsive">
        <thead>
            <tr>
                <th>Auth Data</th>
                <th>Email</th>
                <th>Username</th>
                <th>Other Fields</th>
                <th class="blank"></th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>
<div class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="submit btn btn-primary">Save changes</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
